/* Generated from Java with JSweet 2.0.0-rc1 - http://www.jsweet.org */
namespace uml {
    /**
     * <!-- begin-user-doc -->
     * A representation of the literals of the enumeration '<em><b>Message Sort</b></em>',
     * and utility methods for working with them.
     * <!-- end-user-doc -->
     * <!-- begin-model-doc -->
     * This is an enumerated type that identifies the type of communication action that was used to generate the Message.
     * <p>From package UML::Interactions.</p>
     * <!-- end-model-doc -->
     * @see uml.UmlPackage#getMessageSort()
     * @model
     * @generated
     * @enum
     * @property {uml.MessageSort} SYNCH_CALL
     * The '<em><b>Synch Call</b></em>' literal object.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see #SYNCH_CALL_VALUE
     * @generated
     * @ordered
     * @property {uml.MessageSort} ASYNCH_CALL
     * The '<em><b>Asynch Call</b></em>' literal object.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see #ASYNCH_CALL_VALUE
     * @generated
     * @ordered
     * @property {uml.MessageSort} ASYNCH_SIGNAL
     * The '<em><b>Asynch Signal</b></em>' literal object.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see #ASYNCH_SIGNAL_VALUE
     * @generated
     * @ordered
     * @property {uml.MessageSort} CREATE_MESSAGE
     * The '<em><b>Create Message</b></em>' literal object.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see #CREATE_MESSAGE_VALUE
     * @generated
     * @ordered
     * @property {uml.MessageSort} DELETE_MESSAGE
     * The '<em><b>Delete Message</b></em>' literal object.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see #DELETE_MESSAGE_VALUE
     * @generated
     * @ordered
     * @property {uml.MessageSort} REPLY
     * The '<em><b>Reply</b></em>' literal object.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see #REPLY_VALUE
     * @generated
     * @ordered
     * @property {number} SYNCH_CALL_VALUE
     * The '<em><b>Synch Call</b></em>' literal value.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * <!-- begin-model-doc -->
     * The message was generated by a synchronous call to an operation.
     * <!-- end-model-doc -->
     * @see #SYNCH_CALL
     * @model name="synchCall"
     * @generated
     * @ordered
     * @property {number} ASYNCH_CALL_VALUE
     * The '<em><b>Asynch Call</b></em>' literal value.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * <!-- begin-model-doc -->
     * The message was generated by an asynchronous call to an operation; i.e., a CallAction with isSynchronous = false.
     * <!-- end-model-doc -->
     * @see #ASYNCH_CALL
     * @model name="asynchCall"
     * @generated
     * @ordered
     * @property {number} ASYNCH_SIGNAL_VALUE
     * The '<em><b>Asynch Signal</b></em>' literal value.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * <!-- begin-model-doc -->
     * The message was generated by an asynchronous send action.
     * <!-- end-model-doc -->
     * @see #ASYNCH_SIGNAL
     * @model name="asynchSignal"
     * @generated
     * @ordered
     * @property {number} CREATE_MESSAGE_VALUE
     * The '<em><b>Create Message</b></em>' literal value.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * <!-- begin-model-doc -->
     * The message designating the creation of another lifeline object.
     * <!-- end-model-doc -->
     * @see #CREATE_MESSAGE
     * @model name="createMessage"
     * @generated
     * @ordered
     * @property {number} DELETE_MESSAGE_VALUE
     * The '<em><b>Delete Message</b></em>' literal value.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * <!-- begin-model-doc -->
     * The message designating the termination of another lifeline.
     * <!-- end-model-doc -->
     * @see #DELETE_MESSAGE
     * @model name="deleteMessage"
     * @generated
     * @ordered
     * @property {number} REPLY_VALUE
     * The '<em><b>Reply</b></em>' literal value.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * <!-- begin-model-doc -->
     * The message is a reply message to an operation call.
     * <!-- end-model-doc -->
     * @see #REPLY
     * @model name="reply"
     * @generated
     * @ordered
     * @property {uml.MessageSort[]} VALUES
     * A public read-only list of all the '<em><b>Message Sort</b></em>' enumerators.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     * @class
     */
    export enum MessageSort {
        
        /**
         * The '<em><b>Synch Call</b></em>' literal object.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @see #SYNCH_CALL_VALUE
         * @generated
         * @ordered
         */
        SYNCH_CALL, 
        /**
         * The '<em><b>Asynch Call</b></em>' literal object.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @see #ASYNCH_CALL_VALUE
         * @generated
         * @ordered
         */
        ASYNCH_CALL, 
        /**
         * The '<em><b>Asynch Signal</b></em>' literal object.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @see #ASYNCH_SIGNAL_VALUE
         * @generated
         * @ordered
         */
        ASYNCH_SIGNAL, 
        /**
         * The '<em><b>Create Message</b></em>' literal object.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @see #CREATE_MESSAGE_VALUE
         * @generated
         * @ordered
         */
        CREATE_MESSAGE, 
        /**
         * The '<em><b>Delete Message</b></em>' literal object.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @see #DELETE_MESSAGE_VALUE
         * @generated
         * @ordered
         */
        DELETE_MESSAGE, 
        /**
         * The '<em><b>Reply</b></em>' literal object.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @see #REPLY_VALUE
         * @generated
         * @ordered
         */
        REPLY
    }

    /** @ignore */
    export class MessageSort_$WRAPPER implements org.eclipse.emf.common.util.Enumerator {
        /**
         * The '<em><b>Synch Call</b></em>' literal value.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * <!-- begin-model-doc -->
         * The message was generated by a synchronous call to an operation.
         * <!-- end-model-doc -->
         * @see #SYNCH_CALL
         * @model name="synchCall"
         * @generated
         * @ordered
         */
        public static SYNCH_CALL_VALUE = 0;

        /**
         * The '<em><b>Asynch Call</b></em>' literal value.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * <!-- begin-model-doc -->
         * The message was generated by an asynchronous call to an operation; i.e., a CallAction with isSynchronous = false.
         * <!-- end-model-doc -->
         * @see #ASYNCH_CALL
         * @model name="asynchCall"
         * @generated
         * @ordered
         */
        public static ASYNCH_CALL_VALUE = 1;

        /**
         * The '<em><b>Asynch Signal</b></em>' literal value.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * <!-- begin-model-doc -->
         * The message was generated by an asynchronous send action.
         * <!-- end-model-doc -->
         * @see #ASYNCH_SIGNAL
         * @model name="asynchSignal"
         * @generated
         * @ordered
         */
        public static ASYNCH_SIGNAL_VALUE = 2;

        /**
         * The '<em><b>Create Message</b></em>' literal value.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * <!-- begin-model-doc -->
         * The message designating the creation of another lifeline object.
         * <!-- end-model-doc -->
         * @see #CREATE_MESSAGE
         * @model name="createMessage"
         * @generated
         * @ordered
         */
        public static CREATE_MESSAGE_VALUE = 3;

        /**
         * The '<em><b>Delete Message</b></em>' literal value.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * <!-- begin-model-doc -->
         * The message designating the termination of another lifeline.
         * <!-- end-model-doc -->
         * @see #DELETE_MESSAGE
         * @model name="deleteMessage"
         * @generated
         * @ordered
         */
        public static DELETE_MESSAGE_VALUE = 4;

        /**
         * The '<em><b>Reply</b></em>' literal value.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * <!-- begin-model-doc -->
         * The message is a reply message to an operation call.
         * <!-- end-model-doc -->
         * @see #REPLY
         * @model name="reply"
         * @generated
         * @ordered
         */
        public static REPLY_VALUE = 5;

        /**
         * An array of all the '<em><b>Message Sort</b></em>' enumerators.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @generated
         */
        static VALUES_ARRAY; public static VALUES_ARRAY_$LI$() : MessageSort[] { if(MessageSort_$WRAPPER.VALUES_ARRAY == null) MessageSort_$WRAPPER.VALUES_ARRAY = [MessageSort.SYNCH_CALL, MessageSort.ASYNCH_CALL, MessageSort.ASYNCH_SIGNAL, MessageSort.CREATE_MESSAGE, MessageSort.DELETE_MESSAGE, MessageSort.REPLY]; return MessageSort_$WRAPPER.VALUES_ARRAY; };

        /**
         * A public read-only list of all the '<em><b>Message Sort</b></em>' enumerators.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @generated
         */
        public static VALUES; public static VALUES_$LI$() : Array<MessageSort> { if(MessageSort_$WRAPPER.VALUES == null) MessageSort_$WRAPPER.VALUES = /* unmodifiableList *//* asList */MessageSort_$WRAPPER.VALUES_ARRAY_$LI$().slice(0).slice(0); return MessageSort_$WRAPPER.VALUES; };

        public static get$java_lang_String(literal) : MessageSort {
            for(let i = 0; i < MessageSort_$WRAPPER.VALUES_ARRAY_$LI$().length; ++i) {
                let result = MessageSort_$WRAPPER.VALUES_ARRAY_$LI$()[i];
                if(/* equals */(<any>((o1: any, o2: any) => { if(o1 && o1.equals) { return o1.equals(o2); } else { return o1 === o2; } })(uml.MessageSort["_$wrappers"][result].toString(),literal))) {
                    return result;
                }
            };
            return null;
        }

        /**
         * Returns the '<em><b>Message Sort</b></em>' literal with the specified literal value.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @param {string} literal the literal.
         * @return {uml.MessageSort} the matching enumerator or <code>null</code>.
         * @generated
         */
        public static get(literal?) : any {
            if(((typeof literal === 'string') || literal === null)) {
                return <any>uml.MessageSort_$WRAPPER.get$java_lang_String(literal);
            } else if(((typeof literal === 'number') || literal === null)) {
                return <any>uml.MessageSort_$WRAPPER.get$int(literal);
            } else throw new Error('invalid overload');
        }

        /**
         * Returns the '<em><b>Message Sort</b></em>' literal with the specified name.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @param {string} name the name.
         * @return {uml.MessageSort} the matching enumerator or <code>null</code>.
         * @generated
         */
        public static getByName(name) : MessageSort {
            for(let i = 0; i < MessageSort_$WRAPPER.VALUES_ARRAY_$LI$().length; ++i) {
                let result = MessageSort_$WRAPPER.VALUES_ARRAY_$LI$()[i];
                if(/* equals */(<any>((o1: any, o2: any) => { if(o1 && o1.equals) { return o1.equals(o2); } else { return o1 === o2; } })(uml.MessageSort["_$wrappers"][result].getName(),name))) {
                    return result;
                }
            };
            return null;
        }

        public static get$int(value) : MessageSort {
            switch((value)) {
            case 0 /* SYNCH_CALL_VALUE */:
                return MessageSort.SYNCH_CALL;
            case 1 /* ASYNCH_CALL_VALUE */:
                return MessageSort.ASYNCH_CALL;
            case 2 /* ASYNCH_SIGNAL_VALUE */:
                return MessageSort.ASYNCH_SIGNAL;
            case 3 /* CREATE_MESSAGE_VALUE */:
                return MessageSort.CREATE_MESSAGE;
            case 4 /* DELETE_MESSAGE_VALUE */:
                return MessageSort.DELETE_MESSAGE;
            case 5 /* REPLY_VALUE */:
                return MessageSort.REPLY;
            }
            return null;
        }

        /**
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @generated
         */
        /*private*/ value;

        /**
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @generated
         */
        /*private*/ __name;

        /**
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @generated
         */
        /*private*/ literal;

        constructor(protected _$ordinal : number, protected _$name : string, value, name, literal) {
            this.value = 0;
            this.__name = null;
            this.literal = null;
            this.value = value;
            this.__name = name;
            this.literal = literal;
        }

        /**
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @generated
         * @return {number}
         */
        public getValue() : number {
            return this.value;
        }

        /**
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @generated
         * @return {string}
         */
        public getName() : string {
            return this.__name;
        }

        /**
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @generated
         * @return {string}
         */
        public getLiteral() : string {
            return this.literal;
        }

        /**
         * Returns the literal value of the enumerator, which is its string representation.
         * <!-- begin-user-doc -->
         * <!-- end-user-doc -->
         * @generated
         * @return {string}
         */
        public toString() : string {
            return this.literal;
        }
        public name() : string { return this._$name; }
        public ordinal() : number { return this._$ordinal; }
    }
    MessageSort["__class"] = "uml.MessageSort";
    MessageSort["__interfaces"] = ["org.eclipse.emf.common.util.Enumerator","java.lang.Comparable","java.io.Serializable"];

    MessageSort["_$wrappers"] = [new MessageSort_$WRAPPER(0, "SYNCH_CALL", 0, "synchCall", "synchCall"), new MessageSort_$WRAPPER(1, "ASYNCH_CALL", 1, "asynchCall", "asynchCall"), new MessageSort_$WRAPPER(2, "ASYNCH_SIGNAL", 2, "asynchSignal", "asynchSignal"), new MessageSort_$WRAPPER(3, "CREATE_MESSAGE", 3, "createMessage", "createMessage"), new MessageSort_$WRAPPER(4, "DELETE_MESSAGE", 4, "deleteMessage", "deleteMessage"), new MessageSort_$WRAPPER(5, "REPLY", 5, "reply", "reply")];

}


uml.MessageSort_$WRAPPER.VALUES_$LI$();

uml.MessageSort_$WRAPPER.VALUES_ARRAY_$LI$();
